gpu_id: 0
model: /results/best_accuracy.tlt
output_file: /results/pruned/amount_0.1.tlt
output_dir: /results/pruned/
encryption_key: nvidia_tao
model_config:
  TPS: True
  backbone: ResNet
  feature_channel: 512
  sequence: BiLSTM
  hidden_size: 256
  prediction: CTC
dataset_config:
  character_list_file: /data/character_list
  img_width: 100
  img_height: 32
  img_channel: 1
  max_label_length: 25
  batch_size: 32
  workers: 4
  augmentation_config:
    keep_aspect_ratio: False
prune_config:
  mode: experimental_hybrid
  amount: 0.4
  granularity: 8
  raw_prune_score: L1
